-- MySQL Script generated by MySQL Workbench
-- Wed Nov  3 23:09:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aspirantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aspirantes` (
  `idAspirantes` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `Género` VARCHAR(10) NULL,
  `Teléfono` VARCHAR(50) NOT NULL,
  `correoElectrónico` VARCHAR(50) NOT NULL,
  `Contraseña` VARCHAR(50) NOT NULL,
  `Escolaridad` VARCHAR(50) NULL,
  `experienciaLaboral` VARCHAR(50) NULL,
  `softSkills` VARCHAR(50) NULL,
  `hardSkills` VARCHAR(50) NULL,
  `Idiomas` VARCHAR(50) NULL,
  `fotoPerfil` VARBINARY(100) NULL,
  PRIMARY KEY (`idAspirantes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Dirección` VARCHAR(50) NULL,
  `informaciónContacto` VARCHAR(50) NULL,
  `correoElectrónico` VARCHAR(50) NOT NULL,
  `Contraseña` VARCHAR(50) NOT NULL,
  `razónSocial` VARCHAR(50) NULL,
  `fotoPerfil` VARBINARY(100) NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleos` (
  `idEmpleos` INT NOT NULL AUTO_INCREMENT,
  `Título` VARCHAR(50) NOT NULL,
  `Ubicación` VARCHAR(50) NULL,
  `Descripción` VARCHAR(50) NULL,
  `Salario` VARCHAR(50) NULL,
  `tipoPuesto` VARCHAR(50) NOT NULL,
  `Idiomas` VARCHAR(50) NULL,
  `Escolaridad` VARCHAR(50) NULL,
  `experienciaLaboral` VARCHAR(50) NULL,
  `softSkills` VARCHAR(50) NULL,
  `hardSkills` VARCHAR(50) NULL,
  `Remoto` TINYINT NULL,
  `fechaPublicación` DATE NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idEmpleos`, `Empresa_idEmpresa`),
  INDEX `fk_Empleos_Empresa1_idx` (`Empresa_idEmpresa` ASC) VISIBLE,
  CONSTRAINT `fk_Empleos_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `mydb`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aspirantes_has_Empleos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aspirantes_has_Empleos` (
  `Aspirantes_idAspirantes` INT NOT NULL,
  `Empleos_idEmpleos` INT NOT NULL,
  `Estado` INT NOT NULL,
  PRIMARY KEY (`Aspirantes_idAspirantes`, `Empleos_idEmpleos`),
  INDEX `fk_Aspirantes_has_Empleos_Empleos1_idx` (`Empleos_idEmpleos` ASC) VISIBLE,
  INDEX `fk_Aspirantes_has_Empleos_Aspirantes_idx` (`Aspirantes_idAspirantes` ASC) VISIBLE,
  CONSTRAINT `fk_Aspirantes_has_Empleos_Aspirantes`
    FOREIGN KEY (`Aspirantes_idAspirantes`)
    REFERENCES `mydb`.`Aspirantes` (`idAspirantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aspirantes_has_Empleos_Empleos1`
    FOREIGN KEY (`Empleos_idEmpleos`)
    REFERENCES `mydb`.`Empleos` (`idEmpleos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'admin' IDENTIFIED BY '123';

GRANT ALL ON `mydb`.* TO 'admin';
GRANT SELECT ON TABLE `mydb`.* TO 'admin';
GRANT SELECT, INSERT, TRIGGER ON TABLE `mydb`.* TO 'admin';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `mydb`.* TO 'admin';
GRANT EXECUTE ON ROUTINE `mydb`.* TO 'admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
