-- MySQL Script generated by MySQL Workbench
-- Thu Nov  4 14:19:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`aspirantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aspirantes` (
  `idAspirantes` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `Género` VARCHAR(10) NULL DEFAULT NULL,
  `Teléfono` VARCHAR(50) NOT NULL,
  `correoElectrónico` VARCHAR(50) NOT NULL,
  `Contraseña` VARCHAR(50) NOT NULL,
  `Escolaridad` VARCHAR(50) NULL DEFAULT NULL,
  `experienciaLaboral` VARCHAR(50) NULL DEFAULT NULL,
  `softSkills` VARCHAR(50) NULL DEFAULT NULL,
  `hardSkills` VARCHAR(50) NULL DEFAULT NULL,
  `Idiomas` VARCHAR(50) NULL DEFAULT NULL,
  `fotoPerfil` VARBINARY(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idAspirantes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NOT NULL,
  `Dirección` VARCHAR(50) NULL DEFAULT NULL,
  `informaciónContacto` VARCHAR(50) NULL DEFAULT NULL,
  `correoElectrónico` VARCHAR(50) NOT NULL,
  `Contraseña` VARCHAR(50) NOT NULL,
  `razónSocial` VARCHAR(50) NULL DEFAULT NULL,
  `fotoPerfil` VARBINARY(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`empleos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleos` (
  `idEmpleos` INT NOT NULL AUTO_INCREMENT,
  `Título` VARCHAR(150) NOT NULL,
  `Ubicación` VARCHAR(50) NULL DEFAULT NULL,
  `Descripción` VARCHAR(15000) NULL DEFAULT NULL,
  `salarioMIN` DECIMAL(10,0) NULL DEFAULT NULL,
  `salarioMAX` DECIMAL(10,0) NULL DEFAULT NULL,
  `tipoPuesto` VARCHAR(50) NOT NULL,
  `Idiomas` VARCHAR(50) NULL DEFAULT NULL,
  `Escolaridad` VARCHAR(100) NULL DEFAULT NULL,
  `experienciaLaboral` VARCHAR(200) NULL DEFAULT NULL,
  `softSkills` VARCHAR(300) NULL DEFAULT NULL,
  `hardSkills` VARCHAR(300) NULL DEFAULT NULL,
  `Remoto` TINYINT NULL DEFAULT NULL,
  `fechaPublicación` DATE NULL DEFAULT NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idEmpleos`, `Empresa_idEmpresa`),
  INDEX `fk_Empleos_Empresa1_idx` (`Empresa_idEmpresa` ASC) VISIBLE,
  CONSTRAINT `fk_Empleos_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `mydb`.`empresa` (`idEmpresa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`aspirantes_has_empleos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aspirantes_has_empleos` (
  `Aspirantes_idAspirantes` INT NOT NULL,
  `Empleos_idEmpleos` INT NOT NULL,
  `Estado` INT NOT NULL,
  PRIMARY KEY (`Aspirantes_idAspirantes`, `Empleos_idEmpleos`),
  INDEX `fk_Aspirantes_has_Empleos_Empleos1_idx` (`Empleos_idEmpleos` ASC) VISIBLE,
  INDEX `fk_Aspirantes_has_Empleos_Aspirantes_idx` (`Aspirantes_idAspirantes` ASC) VISIBLE,
  CONSTRAINT `fk_Aspirantes_has_Empleos_Aspirantes`
    FOREIGN KEY (`Aspirantes_idAspirantes`)
    REFERENCES `mydb`.`aspirantes` (`idAspirantes`),
  CONSTRAINT `fk_Aspirantes_has_Empleos_Empleos1`
    FOREIGN KEY (`Empleos_idEmpleos`)
    REFERENCES `mydb`.`empleos` (`idEmpleos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
